name: Release CV

on: 
  push:
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  build-latex:
    name: Build Latex
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            PanfilyonokCV-ru.tex
            PanfilyonokCV.tex

      - uses: actions/cache@v3.0.3
        with:
          path: |
            PanfilyonokCV-ru.pdf
            PanfilyonokCV.pdf
          key: ${{ github.sha }}
          
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build-latex]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3.0.3
        with:
          path: |
            PanfilyonokCV-ru.pdf
            PanfilyonokCV.pdf
          key: ${{ github.sha }}
          
      - uses: softprops/action-gh-release@v0.1.14
        with:
          files: |
            PanfilyonokCV-ru.pdf
            PanfilyonokCV.pdf
          name: CV
          tag_name: ${{ github.ref }}
          
