name: Release Compiled PDF

on: 
  push:
  workflow_dispatch:

jobs:
  build-latex:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: PanfilyonokCV-ru.tex
#         env:
#           TEXINPUTS: ".:"
        
      - uses: actions/upload-artifact@v2
        with:
          name: cv
          path: PanfilyonokCV-ru.pdf
          
  artifact-use-build:
    name: Re-use Artifact
    runs-on: ubuntu-latest
    needs: [build-latex]
    
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - uses: actions/download-artifact@v2
        with:
          name: cv
          
      - run: unzip cv.zip
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: PanfilyonokCV-ru.pdf
            
