name: Release Compiled PDF

on: 
  push:
  workflow_dispatch:

jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: PanfilyonokCV-ru.tex
          args: "-pdf -file-line-error -interaction=nonstopmode"
        env:
          TEXINPUTS: ".:"
        
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: PanfilyonokCV-ru.pdf
